#!/bin/bash

PREFIX="${PREFIX:-/usr/local}"
PYTHON="${PYTHON:-python3}"

if [[ $(id -u) -ne 0 ]]; then
    _sudo="sudo"
fi

version=$(grep '^__version' specmatch/__init__.py | cut -d '"' -f 2)

"$PYTHON" -m build --wheel
$_sudo "$PYTHON" -m pip install \
    --break-system-packages \
    ./dist/specmatch-$version-*.whl

which update-mime-database &>/dev/null && \
    $_sudo update-mime-database "$PREFIX"/share/mime
which update-desktop-database &>/dev/null && \
    $_sudo update-desktop-database
which gtk-update-icon-cache &>/dev/null && \
    $_sudo gtk-update-icon-cache -q "$PREFIX"/share/icons/hicolor
